### ISSUE TITLE
Searx error when executing 'docker-compose up'

### ISSUE THREAD

**Issue by jezkerwin** [Felix83000/Watcher#18]
When running docker-compose up I'm getting the following error in standard output. 
Not sure if it's causing additional errors.

```
watcher          | [04/Nov/2020 22:04:19] "GET /api/dns_finder/alert/ HTTP/1.1" 200 2
watcher          | [04/Nov/2020 22:04:19] "GET /api/dns_finder/dns_monitored/ HTTP/1.1" 200 2
watcher          | [04/Nov/2020 22:04:25] "POST /api/dns_finder/dns_monitored/ HTTP/1.1" 201 85
searx-checker    | 2020/11/04 11:04:59 Check with the parameters : -o html/data/status.json http://10.10.10.3:8080
searx-checker    | Searx version : 0.17.0-224-1b42d426
searx-checker    | Testing 108 engines of http://10.10.10.3:8080
searx-checker    | This might take a while...
searx-checker    | 1337x.Traceback (most recent call last):
searx-checker    |   File "./checker/checker.py", line 228, in <module>
searx-checker    |     main(args.url, args.o)
searx-checker    |   File "./checker/checker.py", line 215, in main
searx-checker    |     state = check_engines_state(instance_url, engines)
searx-checker    |   File "./checker/checker.py", line 168, in check_engines_state
searx-checker    |     provides_results = _request_results(instance_url, engine)
searx-checker    |   File "./checker/checker.py", line 156, in _request_results
searx-checker    |     engine_result = _query_engine_result(instance_url, engine, query)
searx-checker    |   File "./checker/checker.py", line 146, in _query_engine_result
searx-checker    |     return _check_response(resp)
searx-checker    |   File "./checker/checker.py", line 124, in _check_response
searx-checker    |     resp_json = resp.json()
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
searx-checker    |     return complexjson.loads(self.text, **kwargs)
searx-checker    |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
searx-checker    |     return _default_decoder.decode(s)
searx-checker    |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
searx-checker    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
searx-checker    |   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
searx-checker    |     raise JSONDecodeError("Expecting value", s, err.value) from None
searx-checker    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
searx-checker    | Sleep 86316 seconds
watcher          | 2020-11-04 22:05:00.001430 - CRON TASK : Fetch searx & pastebin
watcher          | 2020-11-04 22:05:00.004532 - Querying Searx for:  "data breach"
```

**Comment by Felix83000** [comment]
This issue comes from **searx-checker** containers (https://github.com/searx/searx-checker).
Probably a network problem.

It **won't impact Watcher** at all.

Regards,
